language: python

python:
  - "2.7"

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo apt-get install python-numpy libgdal1h gdal-bin libgdal-dev libgdal1-dev
  - sudo apt-get install python-gdal

    # rasterio?
  - sudo apt-get install g++

    # numpy (needs fortran to compile)
  - sudo apt-get -y install libblas3gf libc6 libgcc1 libgfortran3 liblapack3gf libstdc++6 build-essential gfortran python-all-dev libatlas-base-dev

    # numpy dependency
  - sudo apt-get -y install python-dev

    # scipy dependency
  - sudo apt-get -y install libblas-dev liblapack-dev
  - gdal-config --version

install:
#  - pip install -r requirements-dev.txt
  - pip install -r requirements-gdal.txt
#  - pip install --no-install GDAL
#  - python setup.py build_ext --include-dirs=<path_to_headers>
#  - pip install --no-download GDAL
  - pip install pytest pytest-cov
  - pip install -e .

script:
  - py.test --cov geobricks_gis_raster/core --cov-report term-missing
  #- nosetests -v geobricks_gis_raster_test/core/raster_test.py
