language: python

python:
  - "2.7"

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install python-numpy libgdal1h gdal-bin libgdal-dev
  - sudo apt-get install python-gdal
  - sudo apt-get install libblas-dev liblapack-dev

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements-gdal.txt
  - pip install pytest pytest-cov
  - pip install -e .

script:
  - py.test --cov geobricks_gis_raster/core --cov-report term-missing
  #- nosetests -v geobricks_gis_raster_test/core/raster_test.py
